--DESAFIO .NET BANCO DE DADOS

--BUSCAR O NOME E ANO DOS FILMES
SELECT Nome, Ano
FROM Filmes;

--BUSCAR NOME E ANO DOS FILMES, ORDENADOS DE FORMA CRESCENTE
SELECT Nome, Ano
FROM Filmes
ORDER BY Ano ASC;

--BUSCAR O FILME DE VOLTA PARA O FUTURO, TRAZENDO NOME, ANO E DURAÇÃO
SELECT Nome, Ano, Duracao
FROM Filmes
WHERE Nome = 'De Volta para o Futuro';

--BUSCAR FILMES LANÇADOS EM 1997
SELECT Nome, Ano, Duracao
FROM Filmes
WHERE Ano = 1997;

--BUSCAR FILMES LANÇADOS APÓS O ANO 2000
SELECT Nome, Ano, Duracao
FROM Filmes
WHERE Ano > 2000;

--BUSCAR OS FLIMES COM DURACAO MAIOR QUE 100 E MENOR QUE 150, EM ORDEM CRESCENTE
SELECT * FROM FILMES
WHERE Duracao > 100 AND Duracao < 150
ORDER BY Duracao ASC;

--BUSCAR QUANTIDADE DE FILMES LANÇADOS NO ANO, AGRUPANDO POR ANO E ORDENANDO POR ORDEM DECRESCENTE
SELECT Ano, COUNT(*) AS QuantidadeFilmes
FROM Filmes
GROUP BY Ano
ORDER BY QuantidadeFilmes DESC;

--BUSCAR ATORES DO GÊNERO MASCULINO, RETORNANDO PRIMEIRO NOME E ULTIMO NOME
SELECT PrimeiroNome, UltimoNome, Genero
FROM Atores
WHERE Genero = 'M';

--BUSCAR ATRIZES DO GÊNERO FEMININO, RETORNANDO O PRIMEIRO NOME E ULTIMO NOME, ORDENANDO PELO PRIMEIRO NOME
SELECT PrimeiroNome, UltimoNome, Genero
FROM Atores
WHERE Genero = 'F'
ORDER BY PrimeiroNome;

--BUSCAR NOME DO FILME E O GÊNERO
SELECT F.Nome, G.Genero
FROM Filmes F
JOIN FilmesGenero FG ON F.Id = FG.IdFilme
JOIN Generos G ON FG.IdGenero = G.Id

--BUSCAR O NOME DO FILME E O GÊNERO DO TIPO "Misterio"
SELECT F.Nome, G.Genero
FROM Filmes F
JOIN FilmesGenero FG ON F.Id = FG.IdFilme
JOIN Generos G ON FG.IdGenero = G.Id
WHERE G.Genero = 'Mistério';

--BUSCAR O NOME DO FILME E OS ATORES, TRAZENDO O PRIMEIRO NOME, ULTIMO NOME E O SEU PAPEL
SELECT F.Nome, A.PrimeiroNome, A.UltimoNome, EF.Papel
FROM Filmes F
JOIN ElencoFilme EF ON F.Id = EF.IdFilme
JOIN Atores A ON EF.IdAtor = A.Id;